[package]
name = "flake-input-modifier"
version.workspace = true
edition.workspace = true

[lib]
name = "flake_input_modifier"
path = "src/lib.rs"

[[bin]]
name = "flake-input-modifier"
path = "src/main.rs"

[dependencies]
rnix = { workspace = true }
rowan = { workspace = true }
clap = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }