//! Multi-repository workspace management
//!
//! This module provides the core functionality for managing workspaces containing
//! multiple git repositories. A workspace is a collection of repositories checked out
//! at specific branches or commits, enabling consistent development environments across
//! multiple related projects.

use crate::config::RepoConfig;
use anyhow::Result;
use std::path::{Path, PathBuf};

// mockall is test-only
#[cfg(test)]
use mockall::automock;

// ============================================================================
// Trait Abstractions
// ============================================================================

/// Git repository operations abstraction for testing
///
/// This trait abstracts git operations to enable mocking in unit tests.
/// Production code uses `RealRepositoryOps` with actual git operations,
/// while tests use `MockRepositoryOps` generated by mockall.
#[cfg_attr(test, automock)]
pub trait RepositoryOps: Send + Sync {
    /// Clone a repository to the specified path and checkout the given branch
    fn clone_repo(&self, url: &str, path: &Path, branch: &str) -> Result<()>;

    /// Pull updates from the remote repository
    fn pull(&self, path: &Path) -> Result<()>;

    /// Get the current status of the repository
    fn get_status(&self, path: &Path) -> Result<RepoStatus>;

    /// Get the current branch name
    fn get_current_branch(&self, path: &Path) -> Result<String>;

    /// Checkout a specific reference (branch, tag, or commit)
    fn checkout_ref(&self, path: &Path, reference: &str) -> Result<()>;

    /// Check if a path contains a valid git repository
    fn is_repo(&self, path: &Path) -> bool;
}

/// Workspace management operations
///
/// This trait defines the core workspace management API. It provides methods
/// for creating, switching, syncing, and removing workspaces.
#[cfg_attr(test, automock)]
pub trait WorkspaceManager {
    /// Switch to a workspace (create if it doesn't exist)
    ///
    /// Creates a new workspace with the given name, cloning all repositories
    /// specified in the config. If the workspace already exists, this is a no-op.
    fn switch(&self, workspace_name: &str, config: &WorkspaceConfig) -> Result<SwitchReport>;

    /// Synchronize a workspace by pulling updates from all repositories
    ///
    /// Pulls updates from remote repositories for all non-pinned repos in the workspace.
    fn sync(&self, workspace_name: &str) -> Result<SyncReport>;

    /// List all available workspaces
    fn list(&self) -> Result<Vec<WorkspaceInfo>>;

    /// Remove a workspace
    fn remove(&self, workspace_name: &str) -> Result<()>;

    /// Execute a command in each repository of the workspace
    fn foreach(&self, workspace_name: &str, command: &[String]) -> Result<ForeachResult>;

    /// Get status of workspace(s)
    ///
    /// If workspace_name is None, returns status of all workspaces.
    /// If specified, returns status of the named workspace only.
    fn status(&self, workspace_name: Option<String>) -> Result<StatusReport>;
}

// ============================================================================
// Domain Types
// ============================================================================

/// Configuration for a workspace
#[derive(Debug, Clone)]
pub struct WorkspaceConfig {
    /// List of repositories to include in the workspace
    pub repos: Vec<RepoConfig>,
    /// Base directory for worktrees
    pub worktree_base: PathBuf,
    /// Default branch name
    pub default_branch: String,
}

/// Information about a workspace
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkspaceInfo {
    /// Name of the workspace
    pub name: String,
    /// Path to the workspace directory
    pub path: PathBuf,
    /// Number of repositories in the workspace
    pub repo_count: usize,
}

/// Report from a workspace switch operation
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SwitchReport {
    /// Name of the workspace
    pub workspace_name: String,
    /// Repositories that were newly created
    pub repos_created: Vec<String>,
    /// Repositories that already existed and were skipped
    pub repos_skipped: Vec<String>,
    /// Errors encountered during switch (repo name, error message)
    pub errors: Vec<(String, String)>,
}

/// Report from a workspace sync operation
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SyncReport {
    /// Name of the workspace
    pub workspace_name: String,
    /// Repositories that were updated
    pub repos_updated: Vec<String>,
    /// Repositories that were skipped because they're pinned
    pub repos_pinned: Vec<String>,
    /// Repositories that failed to update (repo name, error message)
    pub repos_failed: Vec<(String, String)>,
}

/// Result from a foreach operation
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ForeachResult {
    /// Outputs from each repository command execution
    pub outputs: Vec<RepoCommandOutput>,
    /// Failures (repo name, error message)
    pub failures: Vec<(String, String)>,
}

/// Output from executing a command in a repository
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RepoCommandOutput {
    /// Name of the repository
    pub repo_name: String,
    /// Standard output from the command
    pub stdout: String,
    /// Standard error from the command
    pub stderr: String,
    /// Exit code from the command
    pub exit_code: i32,
}

/// Status of a repository
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RepoStatus {
    /// Repository is clean with no modifications
    Clean {
        /// Current branch name
        branch: String,
    },
    /// Repository has modified files
    Modified {
        /// Current branch name
        branch: String,
        /// Number of changes
        changes: usize,
    },
    /// Repository has untracked files
    Untracked {
        /// Current branch name
        branch: String,
        /// Number of untracked files
        files: usize,
    },
    /// Repository is not initialized (no commits)
    Uninitialized,
    /// Repository is broken or corrupted
    Broken {
        /// Reason for the broken state
        reason: String,
    },
    /// Repository is in detached HEAD state
    DetachedHead {
        /// Current commit hash
        commit: String,
    },
}

/// Status report for one or more workspaces
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StatusReport {
    /// Status of each workspace
    pub workspaces: Vec<WorkspaceStatus>,
}

/// Status of a single workspace
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkspaceStatus {
    /// Name of the workspace
    pub name: String,
    /// Status of each repository in the workspace
    pub repos: Vec<RepositoryStatus>,
}

/// Status of a repository within a workspace
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RepositoryStatus {
    /// Name of the repository
    pub name: String,
    /// Status information
    pub status: RepoStatus,
}

// ============================================================================
// Builder Pattern for WorkspaceConfig
// ============================================================================

/// Builder for creating WorkspaceConfig instances
///
/// Provides a fluent API for constructing workspace configurations in tests.
#[derive(Debug, Default)]
pub struct WorkspaceConfigBuilder {
    repos: Vec<RepoConfig>,
    worktree_base: Option<PathBuf>,
    default_branch: String,
}

impl WorkspaceConfigBuilder {
    /// Create a new builder with default values
    pub fn new() -> Self {
        Self {
            repos: Vec::new(),
            worktree_base: None,
            default_branch: "main".to_string(),
        }
    }

    /// Add a repository with a specific branch
    pub fn add_repo(mut self, url: impl Into<String>, branch: impl Into<String>) -> Self {
        self.repos.push(RepoConfig {
            url: url.into(),
            branch: branch.into(),
            git_ref: None,
        });
        self
    }

    /// Add a pinned repository (specific tag or commit)
    pub fn add_pinned_repo(mut self, url: impl Into<String>, reference: impl Into<String>) -> Self {
        self.repos.push(RepoConfig {
            url: url.into(),
            branch: "main".to_string(), // Default branch for pinned repos
            git_ref: Some(reference.into()),
        });
        self
    }

    /// Set the worktree base directory
    pub fn worktree_base(mut self, path: PathBuf) -> Self {
        self.worktree_base = Some(path);
        self
    }

    /// Set the default branch name
    pub fn default_branch(mut self, branch: impl Into<String>) -> Self {
        self.default_branch = branch.into();
        self
    }

    /// Build the final WorkspaceConfig
    pub fn build(self) -> WorkspaceConfig {
        WorkspaceConfig {
            repos: self.repos,
            worktree_base: self
                .worktree_base
                .unwrap_or_else(|| PathBuf::from("worktrees")),
            default_branch: self.default_branch,
        }
    }
}

// ============================================================================
// Skeleton Implementation (Phase 4 - Design Only)
// ============================================================================

/// Real implementation of RepositoryOps using libgit2
pub struct RealRepositoryOps;

impl RealRepositoryOps {
    /// Create a new instance
    pub fn new() -> Self {
        Self
    }
}

impl Default for RealRepositoryOps {
    fn default() -> Self {
        Self::new()
    }
}

impl RepositoryOps for RealRepositoryOps {
    fn clone_repo(&self, _url: &str, _path: &Path, _branch: &str) -> Result<()> {
        unimplemented!("Phase 6: Implement git clone operations")
    }

    fn pull(&self, _path: &Path) -> Result<()> {
        unimplemented!("Phase 6: Implement git pull operations")
    }

    fn get_status(&self, _path: &Path) -> Result<RepoStatus> {
        unimplemented!("Phase 6: Implement git status operations")
    }

    fn get_current_branch(&self, _path: &Path) -> Result<String> {
        unimplemented!("Phase 6: Implement get current branch")
    }

    fn checkout_ref(&self, _path: &Path, _reference: &str) -> Result<()> {
        unimplemented!("Phase 6: Implement git checkout")
    }

    fn is_repo(&self, _path: &Path) -> bool {
        unimplemented!("Phase 6: Implement repository detection")
    }
}

/// Implementation of WorkspaceManager
pub struct WorkspaceManagerImpl {
    repo_ops: Box<dyn RepositoryOps>,
}

impl WorkspaceManagerImpl {
    /// Create a new workspace manager with custom repository operations
    pub fn new(repo_ops: Box<dyn RepositoryOps>) -> Self {
        Self { repo_ops }
    }

    /// Create a new workspace manager with real git operations
    pub fn new_with_real_git() -> Self {
        Self::new(Box::new(RealRepositoryOps::new()))
    }
}

impl WorkspaceManager for WorkspaceManagerImpl {
    fn switch(&self, _workspace_name: &str, _config: &WorkspaceConfig) -> Result<SwitchReport> {
        unimplemented!("Phase 6: Implement workspace switch")
    }

    fn sync(&self, _workspace_name: &str) -> Result<SyncReport> {
        unimplemented!("Phase 6: Implement workspace sync")
    }

    fn list(&self) -> Result<Vec<WorkspaceInfo>> {
        unimplemented!("Phase 6: Implement workspace list")
    }

    fn remove(&self, _workspace_name: &str) -> Result<()> {
        unimplemented!("Phase 6: Implement workspace remove")
    }

    fn foreach(&self, _workspace_name: &str, _command: &[String]) -> Result<ForeachResult> {
        unimplemented!("Phase 6: Implement foreach command")
    }

    fn status(&self, _workspace_name: Option<String>) -> Result<StatusReport> {
        unimplemented!("Phase 6: Implement status command")
    }
}

// ============================================================================
// Unit Tests (Using Mocks)
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use mockall::predicate::*;

    #[test]
    #[should_panic(expected = "Phase 6: Implement workspace sync")]
    fn test_sync_skips_pinned_repos() {
        // Test that sync() calls pull only on non-pinned repos
        // Workspace has 3 repos: repo-a, repo-b (normal), repo-c (pinned)

        // Arrange
        let mut mock_ops = MockRepositoryOps::new();

        // Expect pull only on non-pinned repos
        mock_ops
            .expect_pull()
            .with(eq(Path::new("/worktrees/main/repo-a")))
            .times(1)
            .returning(|_| Ok(()));

        mock_ops
            .expect_pull()
            .with(eq(Path::new("/worktrees/main/repo-b")))
            .times(1)
            .returning(|_| Ok(()));

        // repo-c is pinned (has git_ref set), should NOT be pulled
        mock_ops
            .expect_pull()
            .with(eq(Path::new("/worktrees/main/repo-c")))
            .times(0);

        let manager = WorkspaceManagerImpl::new(Box::new(mock_ops));

        // Act - will panic with "not yet implemented" in Phase 5
        let result = manager.sync("main").unwrap();

        // Assert - these checks will work in Phase 6 when implemented
        assert_eq!(result.repos_updated.len(), 2);
        assert_eq!(result.repos_pinned, vec!["repo-c"]);
        assert!(result.repos_failed.is_empty());
    }

    #[test]
    #[should_panic(expected = "Phase 6: Implement workspace sync")]
    fn test_sync_handles_pull_failures() {
        // Test that sync() continues on failures and reports them
        // Workspace has 2 repos: one succeeds, one fails

        // Arrange
        let mut mock_ops = MockRepositoryOps::new();

        // First repo succeeds
        mock_ops.expect_pull().times(1).returning(|_| Ok(()));

        // Second repo fails with network error
        mock_ops
            .expect_pull()
            .times(1)
            .returning(|_| Err(anyhow::anyhow!("Network error")));

        let manager = WorkspaceManagerImpl::new(Box::new(mock_ops));

        // Act - will panic with "not yet implemented" in Phase 5
        let result = manager.sync("main").unwrap();

        // Assert - verify partial success is reported correctly
        assert_eq!(result.repos_updated.len(), 1);
        assert_eq!(result.repos_failed.len(), 1);
        assert!(result.repos_failed[0].1.contains("Network error"));
    }

    #[test]
    #[should_panic(expected = "Phase 6: Implement foreach command")]
    fn test_foreach_outside_workspace_errors() {
        // Test that foreach() errors when workspace doesn't exist

        // Arrange
        let mock_ops = MockRepositoryOps::new();
        let manager = WorkspaceManagerImpl::new(Box::new(mock_ops));

        // Act - will panic with "not yet implemented" in Phase 5
        let result = manager.foreach("nonexistent", &["pwd".to_string()]);

        // Assert - should error about nonexistent workspace
        assert!(result.is_err());
        let err_msg = result.unwrap_err().to_string();
        assert!(
            err_msg.contains("not found") || err_msg.contains("does not exist"),
            "Error should mention workspace not found: {}",
            err_msg
        );
    }

    #[test]
    #[should_panic(expected = "Phase 6: Implement workspace switch")]
    fn test_switch_with_empty_config() {
        // Test that switch() succeeds with empty config (no repos)

        // Arrange
        let mock_ops = MockRepositoryOps::new();
        let manager = WorkspaceManagerImpl::new(Box::new(mock_ops));

        let config = WorkspaceConfigBuilder::new()
            .worktree_base(PathBuf::from("/tmp/test"))
            .build();

        // Act - will panic with "not yet implemented" in Phase 5
        let result = manager.switch("main", &config).unwrap();

        // Assert - empty config should create no repos
        assert_eq!(result.repos_created.len(), 0);
        assert_eq!(result.repos_skipped.len(), 0);
        assert!(result.errors.is_empty());
    }

    #[test]
    #[should_panic(expected = "Phase 6: Implement workspace remove")]
    fn test_remove_workspace() {
        // Test that remove() deletes a workspace

        // Arrange
        let mock_ops = MockRepositoryOps::new();
        let manager = WorkspaceManagerImpl::new(Box::new(mock_ops));

        // Act - will panic with "not yet implemented" in Phase 5
        let result = manager.remove("test-workspace");

        // Assert - should succeed
        assert!(result.is_ok(), "Removing workspace should succeed");
    }
}
