//! Multi-repository workspace management
//!
//! This module provides the core functionality for managing workspaces containing
//! multiple git repositories. A workspace is a collection of repositories checked out
//! at specific branches or commits, enabling consistent development environments across
//! multiple related projects.

use crate::config::RepoConfig;
use anyhow::Result;
use std::path::{Path, PathBuf};

// mockall is test-only
#[cfg(test)]
use mockall::automock;

// ============================================================================
// Trait Abstractions
// ============================================================================

/// Git repository operations abstraction for testing
///
/// This trait abstracts git operations to enable mocking in unit tests.
/// Production code uses `RealRepositoryOps` with actual git operations,
/// while tests use `MockRepositoryOps` generated by mockall.
#[cfg_attr(test, automock)]
pub trait RepositoryOps: Send + Sync {
    /// Clone a repository to the specified path and checkout the given branch
    fn clone_repo(&self, url: &str, path: &Path, branch: &str) -> Result<()>;

    /// Pull updates from the remote repository
    /// Returns Ok(true) if changes were pulled, Ok(false) if already up-to-date
    fn pull(&self, path: &Path) -> Result<bool>;

    /// Get the current status of the repository
    fn get_status(&self, path: &Path) -> Result<RepoStatus>;

    /// Get the current branch name
    fn get_current_branch(&self, path: &Path) -> Result<String>;

    /// Checkout a specific reference (branch, tag, or commit)
    fn checkout_ref(&self, path: &Path, reference: &str) -> Result<()>;

    /// Check if a path contains a valid git repository
    fn is_repo(&self, path: &Path) -> bool;
}

/// Workspace management operations
///
/// This trait defines the core workspace management API. It provides methods
/// for creating, switching, syncing, and removing workspaces.
#[cfg_attr(test, automock)]
pub trait WorkspaceManager {
    /// Switch to a workspace (create if it doesn't exist)
    ///
    /// Creates a new workspace with the given name, cloning all repositories
    /// specified in the config. If the workspace already exists, this is a no-op.
    fn switch(&self, workspace_name: &str, config: &WorkspaceConfig) -> Result<SwitchReport>;

    /// Synchronize a workspace by pulling updates from all repositories
    ///
    /// Pulls updates from remote repositories for all non-pinned repos in the workspace.
    fn sync(&self, workspace_name: &str) -> Result<SyncReport>;

    /// List all available workspaces
    fn list(&self) -> Result<Vec<WorkspaceInfo>>;

    /// Remove a workspace
    fn remove(&self, workspace_name: &str) -> Result<()>;

    /// Execute a command in each repository of the workspace
    fn foreach(&self, workspace_name: &str, command: &[String]) -> Result<ForeachResult>;

    /// Get status of workspace(s)
    ///
    /// If workspace_name is None, returns status of all workspaces.
    /// If specified, returns status of the named workspace only.
    fn status(&self, workspace_name: Option<String>) -> Result<StatusReport>;
}

// ============================================================================
// Domain Types
// ============================================================================

/// Configuration for a workspace
#[derive(Debug, Clone)]
pub struct WorkspaceConfig {
    /// List of repositories to include in the workspace
    pub repos: Vec<RepoConfig>,
    /// Base directory for worktrees
    pub worktree_base: PathBuf,
    /// Default branch name
    pub default_branch: String,
}

/// Information about a workspace
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkspaceInfo {
    /// Name of the workspace
    pub name: String,
    /// Path to the workspace directory
    pub path: PathBuf,
    /// Number of repositories in the workspace
    pub repo_count: usize,
}

/// Report from a workspace switch operation
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SwitchReport {
    /// Name of the workspace
    pub workspace_name: String,
    /// Repositories that were newly created
    pub repos_created: Vec<String>,
    /// Repositories that already existed and were skipped
    pub repos_skipped: Vec<String>,
    /// Errors encountered during switch (repo name, error message)
    pub errors: Vec<(String, String)>,
}

/// Report from a workspace sync operation
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SyncReport {
    /// Name of the workspace
    pub workspace_name: String,
    /// Repositories that were updated
    pub repos_updated: Vec<String>,
    /// Repositories that were skipped because they're pinned
    pub repos_pinned: Vec<String>,
    /// Repositories that failed to update (repo name, error message)
    pub repos_failed: Vec<(String, String)>,
}

/// Result from a foreach operation
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ForeachResult {
    /// Outputs from each repository command execution
    pub outputs: Vec<RepoCommandOutput>,
    /// Failures (repo name, error message)
    pub failures: Vec<(String, String)>,
}

/// Output from executing a command in a repository
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RepoCommandOutput {
    /// Name of the repository
    pub repo_name: String,
    /// Standard output from the command
    pub stdout: String,
    /// Standard error from the command
    pub stderr: String,
    /// Exit code from the command
    pub exit_code: i32,
}

/// Status of a repository
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RepoStatus {
    /// Repository is clean with no modifications
    Clean {
        /// Current branch name
        branch: String,
    },
    /// Repository has modified files
    Modified {
        /// Current branch name
        branch: String,
        /// Number of changes
        changes: usize,
    },
    /// Repository has untracked files
    Untracked {
        /// Current branch name
        branch: String,
        /// Number of untracked files
        files: usize,
    },
    /// Repository is not initialized (no commits)
    Uninitialized,
    /// Repository is broken or corrupted
    Broken {
        /// Reason for the broken state
        reason: String,
    },
    /// Repository is in detached HEAD state
    DetachedHead {
        /// Current commit hash
        commit: String,
    },
}

/// Status report for one or more workspaces
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StatusReport {
    /// Status of each workspace
    pub workspaces: Vec<WorkspaceStatus>,
}

/// Status of a single workspace
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkspaceStatus {
    /// Name of the workspace
    pub name: String,
    /// Status of each repository in the workspace
    pub repos: Vec<RepositoryStatus>,
}

/// Status of a repository within a workspace
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RepositoryStatus {
    /// Name of the repository
    pub name: String,
    /// Status information
    pub status: RepoStatus,
}

// ============================================================================
// Builder Pattern for WorkspaceConfig
// ============================================================================

/// Builder for creating WorkspaceConfig instances
///
/// Provides a fluent API for constructing workspace configurations in tests.
#[derive(Debug, Default)]
pub struct WorkspaceConfigBuilder {
    repos: Vec<RepoConfig>,
    worktree_base: Option<PathBuf>,
    default_branch: String,
}

impl WorkspaceConfigBuilder {
    /// Create a new builder with default values
    pub fn new() -> Self {
        Self {
            repos: Vec::new(),
            worktree_base: None,
            default_branch: "main".to_string(),
        }
    }

    /// Add a repository with a specific branch
    pub fn add_repo(mut self, url: impl Into<String>, branch: impl Into<String>) -> Self {
        self.repos.push(RepoConfig {
            url: url.into(),
            branch: branch.into(),
            git_ref: None,
        });
        self
    }

    /// Add a pinned repository (specific tag or commit)
    pub fn add_pinned_repo(mut self, url: impl Into<String>, reference: impl Into<String>) -> Self {
        self.repos.push(RepoConfig {
            url: url.into(),
            branch: "main".to_string(), // Default branch for pinned repos
            git_ref: Some(reference.into()),
        });
        self
    }

    /// Set the worktree base directory
    pub fn worktree_base(mut self, path: PathBuf) -> Self {
        self.worktree_base = Some(path);
        self
    }

    /// Set the default branch name
    pub fn default_branch(mut self, branch: impl Into<String>) -> Self {
        self.default_branch = branch.into();
        self
    }

    /// Build the final WorkspaceConfig
    pub fn build(self) -> WorkspaceConfig {
        WorkspaceConfig {
            repos: self.repos,
            worktree_base: self
                .worktree_base
                .unwrap_or_else(|| PathBuf::from("worktrees")),
            default_branch: self.default_branch,
        }
    }
}

// ============================================================================
// Skeleton Implementation (Phase 4 - Design Only)
// ============================================================================

/// Real implementation of RepositoryOps using libgit2
pub struct RealRepositoryOps;

impl RealRepositoryOps {
    /// Create a new instance
    pub fn new() -> Self {
        Self
    }
}

impl Default for RealRepositoryOps {
    fn default() -> Self {
        Self::new()
    }
}

impl RepositoryOps for RealRepositoryOps {
    fn clone_repo(&self, url: &str, path: &Path, branch: &str) -> Result<()> {
        use git2::{build::RepoBuilder, FetchOptions};

        // Create parent directory if it doesn't exist
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        // Set up fetch options to clone only the specified branch
        let mut fetch_opts = FetchOptions::new();
        // Use default callbacks - no progress tracking for now

        // Clone the repository
        let mut builder = RepoBuilder::new();
        builder.branch(branch);
        builder.fetch_options(fetch_opts);
        builder.clone(url, path)?;

        Ok(())
    }

    fn pull(&self, path: &Path) -> Result<bool> {
        use git2::{BranchType, Repository};

        let repo = Repository::open(path)?;

        // Find the remote (assume "origin")
        let mut remote = repo.find_remote("origin")?;

        // Get current branch name
        let head = repo.head()?;
        let branch_name = head
            .shorthand()
            .ok_or_else(|| anyhow::anyhow!("Could not determine current branch"))?;

        // Fetch from remote
        remote.fetch(&[branch_name], None, None)?;

        // Get the fetch head
        let fetch_head = repo.find_reference("FETCH_HEAD")?;
        let fetch_commit = repo.reference_to_annotated_commit(&fetch_head)?;

        // Perform a fast-forward merge
        let analysis = repo.merge_analysis(&[&fetch_commit])?;

        if analysis.0.is_up_to_date() {
            // Already up to date - no changes
            Ok(false)
        } else if analysis.0.is_fast_forward() {
            // Fast-forward merge - changes pulled
            let mut reference = repo.find_reference(&format!("refs/heads/{}", branch_name))?;
            reference.set_target(fetch_commit.id(), "Fast-forward merge")?;
            repo.set_head(&format!("refs/heads/{}", branch_name))?;
            repo.checkout_head(Some(git2::build::CheckoutBuilder::default().force()))?;
            Ok(true)
        } else {
            Err(anyhow::anyhow!(
                "Cannot fast-forward merge; manual intervention required"
            ))
        }
    }

    fn get_status(&self, path: &Path) -> Result<RepoStatus> {
        use git2::Repository;

        let repo = Repository::open(path)?;

        // Check if repository is initialized (has commits)
        if repo.is_empty()? {
            return Ok(RepoStatus::Uninitialized);
        }

        // Check if HEAD is detached
        if repo.head_detached()? {
            let head = repo.head()?;
            let commit = head.peel_to_commit()?;
            let commit_id = commit.id().to_string();
            return Ok(RepoStatus::DetachedHead {
                commit: commit_id[..7].to_string(), // Short hash
            });
        }

        // Get current branch
        let branch = match self.get_current_branch(path) {
            Ok(b) => b,
            Err(e) => {
                return Ok(RepoStatus::Broken {
                    reason: format!("Cannot determine branch: {}", e),
                })
            }
        };

        // Get status summary
        let statuses = repo.statuses(None)?;

        let mut modified = 0;
        let mut untracked = 0;

        for entry in statuses.iter() {
            let status = entry.status();
            if status.is_wt_modified()
                || status.is_index_modified()
                || status.is_wt_deleted()
                || status.is_index_deleted()
                || status.is_index_new()
            {
                modified += 1;
            }
            if status.is_wt_new() {
                untracked += 1;
            }
        }

        if modified > 0 {
            Ok(RepoStatus::Modified {
                branch,
                changes: modified,
            })
        } else if untracked > 0 {
            Ok(RepoStatus::Untracked {
                branch,
                files: untracked,
            })
        } else {
            Ok(RepoStatus::Clean { branch })
        }
    }

    fn get_current_branch(&self, path: &Path) -> Result<String> {
        use git2::Repository;

        let repo = Repository::open(path)?;
        let head = repo.head()?;

        if let Some(name) = head.shorthand() {
            Ok(name.to_string())
        } else {
            Err(anyhow::anyhow!("Could not determine current branch"))
        }
    }

    fn checkout_ref(&self, path: &Path, reference: &str) -> Result<()> {
        use git2::{build::CheckoutBuilder, Repository};

        let repo = Repository::open(path)?;

        // Try to find the reference (branch, tag, or commit)
        let obj = repo.revparse_single(reference)?;

        // Checkout the reference
        repo.checkout_tree(&obj, Some(CheckoutBuilder::default().force()))?;

        // Update HEAD
        repo.set_head_detached(obj.id())?;

        Ok(())
    }

    fn is_repo(&self, path: &Path) -> bool {
        use git2::Repository;
        Repository::open(path).is_ok()
    }
}

/// Implementation of WorkspaceManager
pub struct WorkspaceManagerImpl {
    repo_ops: Box<dyn RepositoryOps>,
    worktree_base: std::cell::RefCell<Option<PathBuf>>,
}

impl WorkspaceManagerImpl {
    /// Create a new workspace manager with custom repository operations
    pub fn new(repo_ops: Box<dyn RepositoryOps>) -> Self {
        Self {
            repo_ops,
            worktree_base: std::cell::RefCell::new(None),
        }
    }

    /// Create a new workspace manager with real git operations
    pub fn new_with_real_git() -> Self {
        Self::new(Box::new(RealRepositoryOps::new()))
    }

    /// Remember the worktree base from first config
    fn remember_worktree_base(&self, config_base: &Path) {
        let mut base = self.worktree_base.borrow_mut();
        if base.is_none() {
            *base = Some(config_base.to_path_buf());
        }
    }

    /// Get the worktree base path
    fn get_worktree_base(&self) -> Result<PathBuf> {
        self.worktree_base
            .borrow()
            .clone()
            .ok_or_else(|| anyhow::anyhow!("Worktree base not set - call switch() first"))
    }

    /// Save workspace configuration to disk
    fn save_workspace_config(&self, workspace_path: &Path, repos: &[RepoConfig]) -> Result<()> {
        use serde_json;

        // Serialize repos to JSON
        let json = serde_json::to_string_pretty(repos)?;

        // Write to .workspace-config.json in workspace directory
        let config_path = workspace_path.join(".workspace-config.json");
        std::fs::write(config_path, json)?;

        Ok(())
    }

    /// Load workspace configuration from disk
    fn load_workspace_config(&self, workspace_path: &Path) -> Result<Vec<RepoConfig>> {
        use serde_json;

        let config_path = workspace_path.join(".workspace-config.json");

        if !config_path.exists() {
            return Err(anyhow::anyhow!(
                "Workspace config not found at {}",
                config_path.display()
            ));
        }

        let contents = std::fs::read_to_string(&config_path)?;
        let repos: Vec<RepoConfig> = serde_json::from_str(&contents)?;

        Ok(repos)
    }
}

impl WorkspaceManager for WorkspaceManagerImpl {
    fn switch(&self, workspace_name: &str, config: &WorkspaceConfig) -> Result<SwitchReport> {
        // Remember the worktree base for future operations
        self.remember_worktree_base(&config.worktree_base);

        let mut report = SwitchReport {
            workspace_name: workspace_name.to_string(),
            repos_created: Vec::new(),
            repos_skipped: Vec::new(),
            errors: Vec::new(),
        };

        // Create workspace base directory
        let workspace_dir = config.worktree_base.join(workspace_name);
        std::fs::create_dir_all(&workspace_dir)?;

        // Clone each repository in the config
        for repo_config in &config.repos {
            // Extract repo name from URL (last component without .git)
            let repo_name = repo_config
                .url
                .rsplit('/')
                .next()
                .unwrap_or("repo")
                .trim_end_matches(".git");

            let repo_path = workspace_dir.join(repo_name);

            // Skip if repository already exists
            if self.repo_ops.is_repo(&repo_path) {
                report.repos_skipped.push(repo_name.to_string());
                continue;
            }

            // Clone the repository
            match self
                .repo_ops
                .clone_repo(&repo_config.url, &repo_path, &repo_config.branch)
            {
                Ok(_) => {
                    // If there's a specific git_ref (pinned tag/commit), checkout that ref
                    if let Some(git_ref) = &repo_config.git_ref {
                        if let Err(e) = self.repo_ops.checkout_ref(&repo_path, git_ref) {
                            report.errors.push((
                                repo_name.to_string(),
                                format!("Failed to checkout ref {}: {}", git_ref, e),
                            ));
                            continue;
                        }
                    }
                    report.repos_created.push(repo_name.to_string());
                }
                Err(e) => {
                    report
                        .errors
                        .push((repo_name.to_string(), format!("Clone failed: {}", e)));
                }
            }
        }

        // Save workspace config for future sync operations
        if let Err(e) = self.save_workspace_config(&workspace_dir, &config.repos) {
            // Log warning but don't fail - workspace is still usable
            eprintln!("Warning: Failed to save workspace config: {}", e);
        }

        Ok(report)
    }

    fn sync(&self, workspace_name: &str) -> Result<SyncReport> {
        let worktree_base = self.get_worktree_base()?;
        let workspace_dir = worktree_base.join(workspace_name);

        // Check if workspace exists
        if !workspace_dir.exists() {
            return Err(anyhow::anyhow!("Workspace '{}' not found", workspace_name));
        }

        // Load workspace configuration
        let repos = self.load_workspace_config(&workspace_dir)?;

        let mut report = SyncReport {
            workspace_name: workspace_name.to_string(),
            repos_updated: Vec::new(),
            repos_pinned: Vec::new(),
            repos_failed: Vec::new(),
        };

        // Process each repository
        for repo_config in &repos {
            // Extract repo name from URL
            let repo_name = repo_config
                .url
                .rsplit('/')
                .next()
                .unwrap_or("repo")
                .trim_end_matches(".git");

            let repo_path = workspace_dir.join(repo_name);

            // Check if repo is pinned (has git_ref set)
            if repo_config.git_ref.is_some() {
                // Pinned repos are skipped during sync
                report.repos_pinned.push(repo_name.to_string());
                continue;
            }

            // Skip if repository doesn't exist (might have been manually deleted)
            if !self.repo_ops.is_repo(&repo_path) {
                continue;
            }

            // Pull updates for non-pinned repos
            match self.repo_ops.pull(&repo_path) {
                Ok(changed) => {
                    // Only report as updated if changes were actually pulled
                    if changed {
                        report.repos_updated.push(repo_name.to_string());
                    }
                }
                Err(e) => {
                    report
                        .repos_failed
                        .push((repo_name.to_string(), e.to_string()));
                }
            }
        }

        Ok(report)
    }

    fn list(&self) -> Result<Vec<WorkspaceInfo>> {
        let worktree_base = self.get_worktree_base()?;
        let mut workspaces = Vec::new();

        // List directories in worktree_base
        if let Ok(entries) = std::fs::read_dir(&worktree_base) {
            for entry in entries.flatten() {
                if let Ok(metadata) = entry.metadata() {
                    if metadata.is_dir() {
                        let name = entry.file_name().to_string_lossy().to_string();
                        let path = entry.path();

                        // Count repos (directories with .git)
                        let mut repo_count = 0;
                        if let Ok(repo_entries) = std::fs::read_dir(&path) {
                            for repo_entry in repo_entries.flatten() {
                                if repo_entry.path().join(".git").exists() {
                                    repo_count += 1;
                                }
                            }
                        }

                        workspaces.push(WorkspaceInfo {
                            name,
                            path,
                            repo_count,
                        });
                    }
                }
            }
        }

        Ok(workspaces)
    }

    fn remove(&self, workspace_name: &str) -> Result<()> {
        let worktree_base = self.get_worktree_base()?;
        let workspace_path = worktree_base.join(workspace_name);

        if workspace_path.exists() {
            std::fs::remove_dir_all(&workspace_path)?;
        }

        Ok(())
    }

    fn foreach(&self, workspace_name: &str, command: &[String]) -> Result<ForeachResult> {
        let worktree_base = self.get_worktree_base()?;
        let workspace_path = worktree_base.join(workspace_name);

        let mut outputs = Vec::new();
        let mut failures = Vec::new();

        if !workspace_path.exists() {
            return Err(anyhow::anyhow!(
                "Workspace '{}' does not exist",
                workspace_name
            ));
        }

        // Find all repos in workspace
        if let Ok(entries) = std::fs::read_dir(&workspace_path) {
            for entry in entries.flatten() {
                let repo_path = entry.path();
                if self.repo_ops.is_repo(&repo_path) {
                    let repo_name = entry.file_name().to_string_lossy().to_string();

                    // Execute command through shell for environment variable expansion
                    // Join command parts into a single shell command string
                    let shell_command = command.join(" ");

                    match std::process::Command::new("sh")
                        .arg("-c")
                        .arg(&shell_command)
                        .current_dir(&repo_path)
                        .env("name", &repo_name) // Provide $name environment variable
                        .output()
                    {
                        Ok(output) => {
                            outputs.push(RepoCommandOutput {
                                repo_name,
                                stdout: String::from_utf8_lossy(&output.stdout).to_string(),
                                stderr: String::from_utf8_lossy(&output.stderr).to_string(),
                                exit_code: output.status.code().unwrap_or(-1),
                            });
                        }
                        Err(e) => {
                            failures.push((repo_name, e.to_string()));
                        }
                    }
                }
            }
        }

        Ok(ForeachResult { outputs, failures })
    }

    fn status(&self, workspace_name: Option<String>) -> Result<StatusReport> {
        let worktree_base = self.get_worktree_base()?;
        let mut workspaces = Vec::new();

        // Determine which workspaces to check
        let workspace_names: Vec<String> = if let Some(name) = workspace_name {
            vec![name]
        } else {
            // Get all workspaces
            self.list()?.iter().map(|w| w.name.clone()).collect()
        };

        for ws_name in workspace_names {
            let workspace_path = worktree_base.join(&ws_name);
            let mut repos = Vec::new();

            if workspace_path.exists() {
                // Find all repos in workspace
                if let Ok(entries) = std::fs::read_dir(&workspace_path) {
                    for entry in entries.flatten() {
                        let repo_path = entry.path();
                        if self.repo_ops.is_repo(&repo_path) {
                            let repo_name = entry.file_name().to_string_lossy().to_string();
                            let status = self.repo_ops.get_status(&repo_path).unwrap_or(
                                RepoStatus::Broken {
                                    reason: "Could not get status".to_string(),
                                },
                            );

                            repos.push(RepositoryStatus {
                                name: repo_name,
                                status,
                            });
                        }
                    }
                }
            }

            workspaces.push(WorkspaceStatus {
                name: ws_name,
                repos,
            });
        }

        Ok(StatusReport { workspaces })
    }
}

// ============================================================================
// Unit Tests (Using Mocks)
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use mockall::predicate::*;

    #[test]
    fn test_sync_skips_pinned_repos() {
        // Test that sync() errors when config not available
        // NOTE: Full implementation would track pinned repos from config

        // Arrange
        let mock_ops = MockRepositoryOps::new();
        let manager = WorkspaceManagerImpl::new(Box::new(mock_ops));

        // Act - sync() not fully implemented yet
        let result = manager.sync("main");

        // Assert - should error
        assert!(result.is_err());
    }

    #[test]
    fn test_sync_handles_pull_failures() {
        // Test that sync() errors when config not available
        // NOTE: Full implementation would handle pull failures

        // Arrange
        let mock_ops = MockRepositoryOps::new();
        let manager = WorkspaceManagerImpl::new(Box::new(mock_ops));

        // Act - sync() not fully implemented yet
        let result = manager.sync("main");

        // Assert - should error
        assert!(result.is_err());
    }

    #[test]
    fn test_foreach_outside_workspace_errors() {
        // Test that foreach() errors when workspace doesn't exist

        // Arrange
        let mock_ops = MockRepositoryOps::new();
        let manager = WorkspaceManagerImpl::new(Box::new(mock_ops));

        // Act
        let result = manager.foreach("nonexistent", &["pwd".to_string()]);

        // Assert - should error (either about worktree base not set, or workspace not found)
        assert!(result.is_err());
        let err_msg = result.unwrap_err().to_string();
        assert!(
            err_msg.contains("not found")
                || err_msg.contains("does not exist")
                || err_msg.contains("not set"),
            "Error should mention workspace or base not found: {}",
            err_msg
        );
    }

    #[test]
    fn test_switch_with_empty_config() {
        // Test that switch() succeeds with empty config (no repos)

        // Arrange
        let mock_ops = MockRepositoryOps::new();
        let manager = WorkspaceManagerImpl::new(Box::new(mock_ops));

        let config = WorkspaceConfigBuilder::new()
            .worktree_base(PathBuf::from("/tmp/test"))
            .build();

        // Act
        let result = manager.switch("main", &config).unwrap();

        // Assert - empty config should create no repos
        assert_eq!(result.repos_created.len(), 0);
        assert_eq!(result.repos_skipped.len(), 0);
        assert!(result.errors.is_empty());
    }

    #[test]
    fn test_remove_workspace() {
        // Test that remove() errors when worktree base not set

        // Arrange
        let mock_ops = MockRepositoryOps::new();
        let manager = WorkspaceManagerImpl::new(Box::new(mock_ops));

        // Act
        let result = manager.remove("test-workspace");

        // Assert - should error because worktree_base not set
        assert!(result.is_err());
    }
}
